/** Declaration file generated by dts-gen */

// declare module "flic" {

    // class Bridge {
    //     constructor(config: number | { port: number }, cb: any);
    //     close(closeData?: string[]): void;
    // }

    // class Node {
    //     constructor(config?: { [key: string]: any }, ...args: any[]);
    //     leave(force: boolean): this;
    //     shout(...args: any[]): this;
    //     tell(...args: any[]): this;
    // }

    // // deprecated
    // class bridge {
    //     constructor(config: any, cb: any);
    //     close(closeData: any): void;
    // }

    // // deprecated
    // class node {
    //     constructor(config: any, ...args: any[]);
    //     leave(force: any): any;
    //     shout(...args: any[]): any;
    //     tell(...args: any[]): any;
    // }

    // function createBridge(a: any, b: any): Bridge;

    // function createNode(a: string, b: number, c: (msg: string) => void): Node;
// }