/** Declaration file generated by dts-gen */

declare module "limiter" {
    class RateLimiter {
        constructor(
            tokensPerInterval: number,
            interval: string | number,
            fireImmediately?: boolean
        );

        getTokensRemaining(
        ): number;

        removeTokens(
            count: number,
            callback: (err: Error, remainingTokens: number) => void
        ): boolean;

        tryRemoveTokens(
            count: number
        ): boolean;
    }

    class TokenBucket {
        constructor(
            bucketSize: number,
            tokensPerInterval: number,
            interval: string | number,
            parentBucket: TokenBucket
        );

        drip(
        ): boolean;

        removeTokens(
            count: number,
            callback: (err: Error, remainingTokens: number) => void
        ): boolean;

        tryRemoveTokens(
            count: number
        ): boolean;
    }
}