/** Declaration file generated by dts-gen */

export as namespace techan;

export = techan;

declare const techan: {
    accessor: {
        adx: any;
        aroon: any;
        atrtrailingstop: any;
        bollinger: any;
        crosshair: any;
        ichimoku: any;
        macd: any;
        ohlc: any;
        rsi: any;
        stochastic: any;
        supstance: any;
        tick: any;
        trade: any;
        trendline: any;
        value: any;
        volume: any;
        williams: any;
    };
    indicator: {
        adx: any;
        aroon: any;
        atr: any;
        atrtrailingstop: any;
        bollinger: any;
        ema: any;
        heikinashi: any;
        ichimoku: any;
        macd: any;
        rsi: any;
        sma: any;
        stochastic: any;
        vwap: any;
        wilderma: any;
        williams: any;
    };
    plot: {
        adx: any;
        aroon: any;
        atr: any;
        atrtrailingstop: any;
        axisannotation: any;
        bollinger: any;
        candlestick: any;
        close: any;
        crosshair: any;
        ema: any;
        heikinashi: any;
        ichimoku: any;
        macd: any;
        momentum: any;
        moneyflow: any;
        ohlc: any;
        rsi: any;
        sma: any;
        stochastic: any;
        supstance: any;
        tick: any;
        tradearrow: any;
        trendline: any;
        volume: any;
        vwap: any;
        wilderma: any;
        williams: any;
    };
    scale: {
        analysis: {
            supstance: any;
            trendline: any;
        };
        financetime: any;
        plot: {
            adx: any;
            aroon: any;
            atr: any;
            atrtrailingstop: any;
            bollinger: any;
            ichimoku: any;
            macd: any;
            momentum: any;
            moneyflow: any;
            movingaverage: any;
            ohlc: any;
            percent: any;
            rsi: any;
            stochastic: any;
            time: any;
            volume: any;
            williams: any;
        };
        position: {
        };
    };
    svg: {
        arrow: any;
    };
    version: string;
};
